NewsAroundYou/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('newsaroundyouapp.urls')),
]

newsaroundyouapp/urls.py
from django.urls import path
from . import views

app_name = "newsaroundyouapp"
urlpatterns = [
    path("", views.home, name="home"),
    path(
        "category/<str:category>/", views.search_by_category, name="search_by_category"
    ),
    path("search", views.search, name="search"),
    path("error", views.error_page, name="error"),
]

newsaroundyouapp/models.py
from django.db import models

# Create your models here.

newsaroundyouapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
import json
from dotenv import load_dotenv, find_dotenv
import os

env_path = find_dotenv(".env")
load_dotenv(env_path)
API_KEY = os.getenv("API_KEY")


# Create your views here.
def home(request):
    return render(request, "news/home.html")


def search(request):
    search_keyword = request.GET["q"]
    params = {
        "apiKey": API_KEY,
        "q": search_keyword,
        "sortBy": "popularity",
        "pagesize": 20,
        "language": "en",
    }
    API_ENDPOINT = "https://newsapi.org/v2/everything"

    try:
        data = requests.get(API_ENDPOINT, params=params)
        news_collection = data.json()["articles"]

        return render(
            request,
            "news/search.html",
            {"news_collection": news_collection, "search_keyword": search_keyword},
        )
    except KeyError:
        # testing something
        return render(request, "news/error.html")
    except ConnectionError:
        error_page(request)



def search_by_category(request, category):
    API_KEY = "28072e2ae4e1448b96bc16d1300e475e"
    API_ENDPOINT = "https://newsapi.org/v2/top-headlines"
    category = category
    params = {"apiKey": API_KEY, "category": category}

    try:
        data = requests.get(API_ENDPOINT, params=params)
        news = data.json()["articles"]
        return render(
            request,
            "news/category.html",
            {"news_collection": news, "category": category},
        )
    except ConnectionError:
        error_page(request)


def error_page(request):
    return render(request, "news/error.html")

newsaroundyouapp/templates/news/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News Around You</title>
    <!-- <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <link rel="stylesheet" href="{% static 'styles/error.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap');

        * {
            margin: 0;
            padding: 0;
        }


        /* general font */
        * .roboto-slab-uniquifier {
            font-family: "Roboto Slab", serif;
            font-optical-sizing: auto;
            font-style: normal;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            transition: background-color 0.3s, color 0.3s;
        }
        .content {
            max-width: 1500px;
            margin: 10px auto;
        }
        /* Navigation Bar */
        header {
            position: fixed;
            z-index: 1000;
            top: 0;
            background-color: white;
            margin: 0px auto 10px auto;
            padding-bottom: 5px;
            padding-top: 5px;
            width: 100%;
        }
        main {
            z-index: 500;
        }
        nav {
            align-items: center;
            font-size: 14px;
            font-weight: 500;
        }

        nav ul {
            list-style: none;
            display: flex;
            margin: 0;
            padding: 0;
            flex-wrap: wrap;
        }

        nav ul li {
            display: block;
        }
        nav ul li:hover {
            background-color: rgb(0, 174, 255);
            color: white;
        }
        nav ul li a {
            color: #12141a;
            text-decoration: none;
            font-weight: 500;
            cursor: pointer;
            line-height: 18px;
        }
        nav ul li a:hover{
            color: white;
        }
        /* Hero Section */
        .banner {
            text-align: center;
            padding: 100px 20px;
            background-attachment: fixed;
            background-size: cover;
            background-attachment: fixed;
            background-repeat: no-repeat;
            color: black;
            height: 600px;
            width: 95%;
        }
        #title_2 {
            font-weight: 500;
            font-size: 18px;
            font-weight: 400;
            margin-top: 10px;
        }
        #button {
            color: rgb(0, 174, 255);
            font-size: 18px;
            padding: 15px 25px;
            border-radius: 30px;
            border: 0px;
            font-weight: 500;
            font-family: "Roboto Slab", serif;
        }
        #welcome {
            margin: 50px;
            text-align: left;
        }
        .stayinformed {
            font-weight: 500;
            margin-top: 200px;
            margin-bottom: 100px;
        }
        /* Search Bar */
        .search {
            margin-top: 50px;
        }
        .search-bar {
            display: flex;
            align-items: center;
            padding: 10px;
            border: 2px solid #ccc;
            border-radius: 50px;
            width: 500px;
            background: white;
            margin: 20px auto;
        }

        .search-bar input {
            flex-grow: 1;
            border: 0;
            outline: none;
            padding: 8px;
            border-radius: 50px;
            font-family: "Roboto Slab", serif;
            font-size: 14px;
        }

        .recent-articles h2 {
            text-align: center;
            margin: 100px 0px 40px 0px;
        }
        .stayinformed h2 {
            font-size: 40px;
        }

        /* News Section */
        .news-card {
            border-top: 1px solid grey;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .news-image img {
            max-height: 150px;
            object-fit: cover;
        }
        .news-content h3 {
            margin-top: 10px;
            font-size: 1.15rem;
        }
        .news-content h5 {
            font-size: 13px;
            font-weight: 400;
        }
        .card {
            width: 100%;
            display: flex;
            text-decoration: none;
            color: black;
        }
        .news-content {
            margin-left: 30px;
        }
        .news-content p {
            font-size: 15px;
            line-height: 18px;
            font-weight: 400;
            margin-top: 10px;
            color: black
        }
        .news-metadata {
            margin-top: 10px;
            padding-top: 5px;
            padding-bottom: 5px;
        }
        /* pagination */
        .pagination {
            display: none;
            font-family: 'Poppins', sans-serif;
            text-align: center;
        }

        .sources-block {
            text-align: center;
            font-size: 20px;
            border-top: 2px solid rgba(151, 151, 151, 0.763);
        }
        .sources-block h4 {
            padding-top: 40px;
            font-size: 18px;
            font-weight: 500;
            margin: 10px 0px auto;
        }

        a {
            color: rgb(0, 174, 255);
        }
        .sources {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
        }
        .sources li {
            flex-shrink: 1;
            padding: 20px;
            list-style-type: none;
        }
        span {
            color: rgb(0, 174, 255);
        }
        #home {
            display: block;
            border: 1px solid black;
            padding-left: 3px;
            padding-right: 3px;
        }

        /* testing footer placement */
        html, body {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }
        .content {
            flex: 1;
            padding: 20px;
        }
        header {
            display: flex;
            text-align: center;
            align-items: center;
            justify-content: space-around;
            margin-bottom: 40px;
        }
        nav ul li {
            display: inline-block;
            list-style-type: none;
            padding: 10px;
            margin: 10px;
        }
        nav ul {
            display: flex;
        }
        footer {
            height: 80px;
            margin-bottom: 0;
            width: 100%;
            bottom: 0;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            /* border-top: 1px solid rgb(0, 0, 0); */
            background-color: #E5E5E5;
        }
        .stayinformed h1 {
            font-size: 80px;
        }
        .stayinformed h2 {
            font-size: 30px;
        }
    </style>
</head>
<body class="roboto-slab-uniquifier">
    <main class="content">
        <div class="banner">
            <div class="stayinformed">
                <h1><span>503</span></h1>
                <h2>Oops! Rate <span>Limit</span> Reached!</h2>
                <h4 id="title_2">Try Again after some hours!</h4>
                <h5><a href="{% url 'newsaroundyouapp:home' %}">Go Back</a></h5>
            </div>
        </div>
    </main>
</body>
</html>

newsaroundyouapp/templates/news/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News Around You</title>
    <!-- <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap');

        * {
            margin: 0;
            padding: 0;
        }


        /* general font */
        * .roboto-slab-uniquifier {
            font-family: "Roboto Slab", serif;
            font-optical-sizing: auto;
            font-style: normal;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            transition: background-color 0.3s, color 0.3s;
        }
        .content {
            max-width: 1500px;
            margin: 10px auto;
        }
        /* Navigation Bar */
        header {
            position: fixed;
            z-index: 1000;
            top: 0;
            background-color: white;
            margin: 0px auto 10px auto;
            padding-bottom: 5px;
            padding-top: 5px;
            width: 100%;
        }
        main {
            z-index: 500;
        }
        nav {
            align-items: center;
            font-size: 14px;
            font-weight: 500;
        }

        nav ul {
            list-style: none;
            display: flex;
            margin: 0;
            padding: 0;
            flex-wrap: wrap;
        }

        nav ul li {
            display: block;
        }
        nav ul li:hover {
            background-color: rgb(0, 174, 255);
            color: white;
        }
        nav ul li a {
            color: #12141a;
            text-decoration: none;
            font-weight: 500;
            cursor: pointer;
            line-height: 18px;
        }
        nav ul li a:hover{
            color: white;
        }
        /* Hero Section */
        .banner {
            text-align: center;
            padding: 100px 20px;
            background-attachment: fixed;
            background-size: cover;
            background-attachment: fixed;
            background-repeat: no-repeat;
            color: black;
            height: 600px;
            width: 95%;
        }
        #title_2 {
            font-weight: 500;
            font-size: 18px;
            font-weight: 400;
            margin-top: 10px;
        }
        #button {
            color: rgb(0, 174, 255);
            font-size: 18px;
            padding: 15px 25px;
            border-radius: 30px;
            border: 0px;
            font-weight: 500;
            font-family: "Roboto Slab", serif;
        }
        #welcome {
            margin: 50px;
            text-align: left;
        }
        .stayinformed {
            font-weight: 500;
            margin-top: 200px;
            margin-bottom: 100px;
        }
        /* Search Bar */
        .search {
            margin-top: 50px;
        }
        .search-bar {
            display: flex;
            align-items: center;
            padding: 10px;
            border: 2px solid #ccc;
            border-radius: 50px;
            width: 500px;
            background: white;
            margin: 20px auto;
        }

        .search-bar input {
            flex-grow: 1;
            border: 0;
            outline: none;
            padding: 8px;
            border-radius: 50px;
            font-family: "Roboto Slab", serif;
            font-size: 14px;
        }

        .recent-articles h2 {
            text-align: center;
            margin: 100px 0px 40px 0px;
        }
        .stayinformed h2 {
            font-size: 40px;
        }

        /* News Section */
        .news-card {
            border-top: 1px solid grey;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .news-image img {
            max-height: 150px;
            object-fit: cover;
        }
        .news-content h3 {
            margin-top: 10px;
            font-size: 1.15rem;
        }
        .news-content h5 {
            font-size: 13px;
            font-weight: 400;
        }
        .card {
            width: 100%;
            display: flex;
            text-decoration: none;
            color: black;
        }
        .news-content {
            margin-left: 30px;
        }
        .news-content p {
            font-size: 15px;
            line-height: 18px;
            font-weight: 400;
            margin-top: 10px;
            color: black
        }
        .news-metadata {
            margin-top: 10px;
            padding-top: 5px;
            padding-bottom: 5px;
        }
        /* pagination */
        .pagination {
            display: none;
            font-family: 'Poppins', sans-serif;
            text-align: center;
        }

        .sources-block {
            text-align: center;
            font-size: 20px;
            border-top: 2px solid rgba(151, 151, 151, 0.763);
        }
        .sources-block h4 {
            padding-top: 40px;
            font-size: 18px;
            font-weight: 500;
            margin: 10px 0px auto;
        }

        a {
            color: rgb(0, 174, 255);
        }
        .sources {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
        }
        .sources li {
            flex-shrink: 1;
            padding: 20px;
            list-style-type: none;
        }
        span {
            color: rgb(0, 174, 255);
        }
        #home {
            display: block;
            border: 1px solid black;
            padding-left: 3px;
            padding-right: 3px;
        }

        /* testing footer placement */
        html, body {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }
        .content {
            flex: 1;
            padding: 20px;
        }
        header {
            display: flex;
            text-align: center;
            align-items: center;
            justify-content: space-around;
            margin-bottom: 40px;
        }
        nav ul li {
            display: inline-block;
            list-style-type: none;
            padding: 10px;
            margin: 10px;
        }
        nav ul {
            display: flex;
        }
        footer {
            height: 80px;
            margin-bottom: 0;
            width: 100%;
            bottom: 0;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            /* border-top: 1px solid rgb(0, 0, 0); */
            background-color: #E5E5E5;
        }
        .stayinformed h1 {
            font-size: 80px;
        }
        .stayinformed h2 {
            font-size: 30px;
        }
    </style>
</head>
<body class="roboto-slab-uniquifier">
    <header>
        <a href="{% url 'newsaroundyouapp:home' %}"><img src="templates/img/logo.png" alt="" width="150px"></a>
        <nav>
            <ul>
                <li><a href="{% url 'newsaroundyouapp:home' %}" id="home">HOME</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'general' %}">General</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'business' %}">Business</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'entertainment' %}">Entertainment</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'health' %}">Health</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'science' %}">Science</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'sports' %}">Sports</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'technology' %}">Technology</a></li>
            </ul>
        </nav>
    </header>
    <main class="content">
        <div class="banner">
            <div class="stayinformed">
                <h2>Get informed on the <span>topics</span> that <span>matters most</span> to you!</h2>
                <h4 id="title_2">All the way From The world's best sources to here at News Around You!</h4>
            </div>
            <div class="search">
                <h4>Anything you want to know <span>About</span> ?</h4>
                <form action="{% url 'newsaroundyouapp:search' %}" method="GET">
                    <div class="search-bar">
                        <img src="./img/Abc-news-logo.png" alt="search-icon" width="20px" id="search-icon">
                        <input type="search" name="q" id="search_input">
                    </div>
                    <div class="buttons roboto-slab-uniquifier" >
                        <input type="submit" value="Search" id="button">
                    </div>
                </form>
            </div>
        </div>
        <div class="recent-articles">
            {% block news_heading %}
            {% endblock %}
            {% block news_card %}
            {% endblock %}
        </div>
        <div class="pagination">
            <button id="prevPage" disabled>Previous</button>
            <span id="pageNumber">Page 1</span>
            <button id="nextPage">Next</button>
        </div>
    </main>
    <div class="content sources-block">
        <h4>From The world's <span>Trusted</span> Sources</h4>
        <ul class="sources">
            <li><img src="img/BBC-News-Logo-1997.png" alt="" width="110px"></li>
            <li><img src="img/CNN.svg.png" alt="" width="50px"></li>
            <li><img src="img/ESPN_logos.png" alt="" width="100px"></li>
            <li><img src="img/Reuters_Logo.svg.png" width="100px"></li>
            <li><img src="img/Abc-news-logo.png" alt="" width="100px"></li>
            <li><img src="img/france24logo.png" alt="" width="50px"></li>
            <li><img src="img/forbes_logo.png" alt="" width="80px"></li>
            <li><img src="img/washingtonpost_logo.png" alt="" width="200px"></li>
            <li><img src="img/Daily_Mail_masthead.svg" alt="" width="150px"></li>
        </ul>
    </div>
    <footer class="roboto-slab-uniquifier">
        &copy; 2025 News Around You | All rights reserved.
    </footer>
</body>
</html>

newsaroundyouapp/templates/news/noresults.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <link rel="stylesheet" href="{% static 'styles/footer.css' %}"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap');

        * {
            margin: 0;
            padding: 0;
        }


        /* general font */
        * .roboto-slab-uniquifier {
            font-family: "Roboto Slab", serif;
            font-optical-sizing: auto;
            font-style: normal;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            transition: background-color 0.3s, color 0.3s;
        }
        .content {
            max-width: 1500px;
            margin: 10px auto;
        }
        /* Navigation Bar */
        header {
            position: fixed;
            z-index: 1000;
            top: 0;
            background-color: white;
            margin: 0px auto 10px auto;
            padding-bottom: 5px;
            padding-top: 5px;
            width: 100%;
        }
        main {
            z-index: 500;
        }
        nav {
            align-items: center;
            font-size: 14px;
            font-weight: 500;
        }

        nav ul {
            list-style: none;
            display: flex;
            margin: 0;
            padding: 0;
            flex-wrap: wrap;
        }

        nav ul li {
            display: block;
        }
        nav ul li:hover {
            background-color: rgb(0, 174, 255);
            color: white;
        }
        nav ul li a {
            color: #12141a;
            text-decoration: none;
            font-weight: 500;
            cursor: pointer;
            line-height: 18px;
        }
        nav ul li a:hover{
            color: white;
        }
        /* Hero Section */
        .banner {
            text-align: center;
            padding: 100px 20px;
            background-attachment: fixed;
            background-size: cover;
            background-attachment: fixed;
            background-repeat: no-repeat;
            color: black;
            height: 600px;
            width: 95%;
        }
        #title_2 {
            font-weight: 500;
            font-size: 18px;
            font-weight: 400;
            margin-top: 10px;
        }
        #button {
            color: rgb(0, 174, 255);
            font-size: 18px;
            padding: 15px 25px;
            border-radius: 30px;
            border: 0px;
            font-weight: 500;
            font-family: "Roboto Slab", serif;
        }
        #welcome {
            margin: 50px;
            text-align: left;
        }
        .stayinformed {
            font-weight: 500;
            margin-top: 200px;
            margin-bottom: 100px;
        }
        /* Search Bar */
        .search {
            margin-top: 50px;
        }
        .search-bar {
            display: flex;
            align-items: center;
            padding: 10px;
            border: 2px solid #ccc;
            border-radius: 50px;
            width: 500px;
            background: white;
            margin: 20px auto;
        }

        .search-bar input {
            flex-grow: 1;
            border: 0;
            outline: none;
            padding: 8px;
            border-radius: 50px;
            font-family: "Roboto Slab", serif;
            font-size: 14px;
        }

        .recent-articles h2 {
            text-align: center;
            margin: 100px 0px 40px 0px;
        }
        .stayinformed h2 {
            font-size: 40px;
        }

        /* News Section */
        .news-card {
            border-top: 1px solid grey;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .news-image img {
            max-height: 150px;
            object-fit: cover;
        }
        .news-content h3 {
            margin-top: 10px;
            font-size: 1.15rem;
        }
        .news-content h5 {
            font-size: 13px;
            font-weight: 400;
        }
        .card {
            width: 100%;
            display: flex;
            text-decoration: none;
            color: black;
        }
        .news-content {
            margin-left: 30px;
        }
        .news-content p {
            font-size: 15px;
            line-height: 18px;
            font-weight: 400;
            margin-top: 10px;
            color: black
        }
        .news-metadata {
            margin-top: 10px;
            padding-top: 5px;
            padding-bottom: 5px;
        }
        /* pagination */
        .pagination {
            display: none;
            font-family: 'Poppins', sans-serif;
            text-align: center;
        }

        .sources-block {
            text-align: center;
            font-size: 20px;
            border-top: 2px solid rgba(151, 151, 151, 0.763);
        }
        .sources-block h4 {
            padding-top: 40px;
            font-size: 18px;
            font-weight: 500;
            margin: 10px 0px auto;
        }

        a {
            color: rgb(0, 174, 255);
        }
        .sources {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-wrap: wrap;
        }
        .sources li {
            flex-shrink: 1;
            padding: 20px;
            list-style-type: none;
        }
        span {
            color: rgb(0, 174, 255);
        }
        #home {
            display: block;
            border: 1px solid black;
            padding-left: 3px;
            padding-right: 3px;
        }

        /* testing footer placement */
        html, body {
            height: 100%;
            margin: 0;
            display: flex;
            flex-direction: column;
        }
        .content {
            flex: 1;
            padding: 20px;
        }
        header {
            display: flex;
            text-align: center;
            align-items: center;
            justify-content: space-around;
            margin-bottom: 40px;
        }
        nav ul li {
            display: inline-block;
            list-style-type: none;
            padding: 10px;
            margin: 10px;
        }
        nav ul {
            display: flex;
        }
        footer {
            height: 80px;
            margin-bottom: 0;
            width: 100%;
            bottom: 0;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            /* border-top: 1px solid rgb(0, 0, 0); */
            background-color: #E5E5E5;
        }
        .stayinformed h1 {
            font-size: 80px;
        }
        .stayinformed h2 {
            font-size: 30px;
        }
    </style>
</head>
<body class="roboto-slab-uniquifier">
    <header>
        <a href="{% url 'newsaroundyouapp:home' %}"><img src="{% static 'img/logo.png' %}" alt="" width="150px"></a>
        <nav>
            <ul>
                <li><a href="{% url 'newsaroundyouapp:home' %}" id="home">HOME</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'general' %}">General</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'business' %}">Business</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'entertainment' %}">Entertainment</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'health' %}">Health</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'science' %}">Science</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'sports' %}">Sports</a></li>
                <li><a href="{% url 'newsaroundyouapp:search_by_category' 'technology' %}">Technology</a></li>
            </ul>
        </nav>
    </header>
    <main class="content">
        <div class="banner">
            <div class="stayinformed">
                <h2 style="font-size: 20px;">No results for <span>#{{ search_keyword }}</span>!</h2>
            </div>
            <div class="search">
                <h4>Search <span>Again</span> ?</h4>
                <form action="{% url 'newsaroundyouapp:search' %}" method="GET">
                    <div class="search-bar">
                        <img src="{% static 'img/search-i.png' %}" alt="search-icon" width="20px" id="search-icon">
                        <input type="search" name="q" id="search_input">
                    </div>
                    <div class="buttons roboto-slab-uniquifier" >
                        <input type="submit" value="Search" id="button">
                    </div>
                </form>
            </div>
        </div>
    </main>
    <div class="content sources-block">
        <h4>From The world's <span>Trusted</span> Sources</h4>
        <ul class="sources">
            <li><img src="{% static 'img/BBC-News-Logo-1997.png' %}" alt="" width="110px"></li>
            <li><img src="{% static 'img/CNN.svg.png' %}" alt="" width="50px"></li>
            <li><img src="{% static 'img/ESPN_logos.png' %}" alt="" width="100px"></li>
            <li><img src="{% static 'img/Reuters_Logo.svg.png' %}" width="100px"></li>
            <li><img src="{% static 'img/Abc-news-logo.png' %}" alt="" width="100px"></li>
            <li><img src="{% static 'img/france24logo.png' %}" alt="" width="50px"></li>
            <li><img src="{% static 'img/forbes_logo.png' %}" alt="" width="80px"></li>
            <li><img src="{% static 'img/washingtonpost_logo.png' %}" alt="" width="200px"></li>
            <li><img src="{% static 'img/Daily_Mail_masthead.svg' %}" alt="" width="150px"></li>
        </ul>
    </div>
    <footer class="roboto-slab-uniquifier">
        &copy; 2025 News Around You | All rights reserved.
    </footer>
</body>
</html>